### ISSUE TITLE
Cannot compile: qsqlcachedresult_p.h not found

### ISSUE THREAD

**Issue by lschuetze** [sijk/qt5-sqlcipher#4]
I also tried using the Qt 5.2.1 sources from Qt website and my own SqlCipher plug-in but it does give me the same error. I cannot make it compile on Ubuntu 14.04 64bit. qsql_sqlite.cpp depends on an internal header, but that is not found. It resides in `/qtbase/src/sql/kernel/`.

```
/home/lars/Projects/qt5-sqlcipher/qtbase/src/sql/drivers/sqlite/qsql_sqlite.cpp:51:46: fatal error: QtSql/private/qsqlcachedresult_p.h: No such file or directory
 #include <QtSql/private/qsqlcachedresult_p.h>
```

Full console output:
```
g++ -c -m64 -pipe -O2 -fvisibility=hidden -fvisibility-inlines-hidden -std=c++0x -Wall -W -D_REENTRANT -fPIC -DNDEBUG -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_OMIT_COMPLETE -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_RTREE -DSQLITE_DISABLE_LFS -DQT_NO_CAST_TO_ASCII -DQT_NO_CAST_FROM_ASCII -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SQL_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/lars/Projects/qt5-sqlcipher -I/home/lars/Projects/qt5-sqlcipher/qtbase/src/sql/drivers/sqlite -I/home/lars/Projects/qt5-sqlcipher/build/include -I/usr/include/qt5/QtSql/5.2.1 -I/usr/include/qt5/QtSql/5.2.1/QtSql -I/usr/include/qt5 -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore/5.2.1 -I/usr/include/qt5/QtCore/5.2.1/QtCore -I/usr/include/qt5/QtCore -I. -I. -o qsql_sqlite.o /home/lars/Projects/qt5-sqlcipher/qtbase/src/sql/drivers/sqlite/qsql_sqlite.cpp
/home/lars/Projects/qt5-sqlcipher/qtbase/src/sql/drivers/sqlite/qsql_sqlite.cpp:51:46: fatal error: QtSql/private/qsqlcachedresult_p.h: No such file or directory
 #include <QtSql/private/qsqlcachedresult_p.h>
                                              ^
compilation terminated.
```

**Comment by sijk** [comment]
Closing this issue since it's presumably irrelevant with the new build system.
