### ISSUE TITLE
Does not compile with Qt 5.7.0

### ISSUE THREAD

**Issue by blizzard4591** [sijk/qt5-sqlcipher#10]
I assume that some internals have changed.
I get the following error:

> qt-private\qsql_sqlite.cpp(340): error C2664: 'QSqlCachedResult::QSqlCachedResult(const QSqlCachedResult &)': cannot convert argument 1 from 'const QSQLiteDriver *' to 'QSqlCachedResultPrivate &

**Comment by blizzard4591** [comment]
I am so sorry. 
Of course I forgot to replace the Qt private header files, AS NOTED IN THE README.

Then it works.

On Windows, one small change is necessary for it to compile:
qsql_sqlite_p.h Line 61:
Change
`#define Q_EXPORT_SQLDRIVER_SQLITE Q_SQL_EXPORT`
to
`#define Q_EXPORT_SQLDRIVER_SQLITE Q_DECL_EXPORT`

This defines the correct declspec for Exporting to DLL.
